import { createHash } from 'node:crypto';
import { encodeFunctionData, decodeFunctionResult, parseAbi } from 'viem';
import { exactBase } from './exact.js';
import { baseRpc as rpc, RPC_POLICY, sanitizeRpcError } from './rpc.js';

const APPROVED_RUNTIME='0x34f0184b9a8bc2eb9288b1a1fd0433343093485ef3b0628cdb758c9794ac9715';
const USDC='0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913';
const AAVE='0xA238Dd80C259a72e81d7e4664a9801593F98d1c5';
const UNI_V2_ROUTER='0x4752ba5DBc23f44D87826276BF6Fd6b1C372aD24';
const SUSHI_V2_ROUTER='0x6BDED42c6DA8FBf0d2bA55B2fa120C5e0c8D7891';
const UNI_V3_FACTORY='0x33128a8fC17869897dcE68Ed026d694621f6FDfD';
const UNI_V3_ROUTER='0x2626664c2603336E57B271c5C0b26F421741e481';
const AERO_REGISTRY='0x5C3F18F06CC09CA1910767A34a20F771039E37C0';
const AERO_CLASSIC_FACTORY='0x420DD381b31aEf6683db6B902084cB0FFECe40Da';
const AERO_CLASSIC_ROUTER='0xcF77a3Ba9A5CA399B7c97c74d54e5b1Beb874E43';
const AERO_CL_FACTORY='0xf8f2eB4940CFE7d13603DDDD87f123820Fc061Ef';
const AERO_CL_ROUTER='0x698Cb2b6dd822994581fEa6eA4Fc755d1363A92F';
const GPO='0x420000000000000000000000000000000000000F';
const WETH='0x4200000000000000000000000000000000000006';
const norm=x=>String(x||'').toLowerCase(),addr=x=>/^0x[0-9a-fA-F]{40}$/.test(String(x||'')),num=x=>Number.isFinite(Number(x))?Number(x):0;

const receiverAbi=[{type:'function',name:'executeArbitrage',stateMutability:'nonpayable',inputs:[{name:'p',type:'tuple',components:[{name:'quoteToken',type:'address'},{name:'borrow',type:'uint256'},{name:'minProfit',type:'uint256'},{name:'deadline',type:'uint64'},{name:'buy',type:'tuple',components:[{name:'kind',type:'uint8'},{name:'venue',type:'uint8'},{name:'pair',type:'address'},{name:'tokenIn',type:'address'},{name:'tokenOut',type:'address'},{name:'fee',type:'uint24'},{name:'tickSpacing',type:'int24'},{name:'stable',type:'bool'},{name:'minOut',type:'uint256'}]},{name:'sell',type:'tuple',components:[{name:'kind',type:'uint8'},{name:'venue',type:'uint8'},{name:'pair',type:'address'},{name:'tokenIn',type:'address'},{name:'tokenOut',type:'address'},{name:'fee',type:'uint24'},{name:'tickSpacing',type:'int24'},{name:'stable',type:'bool'},{name:'minOut',type:'uint256'}]}]}],outputs:[]}];
const viewAbi=parseAbi(['function owner() view returns(address)','function paused() view returns(bool)','function maxBorrowRaw() view returns(uint256)','function authorizedQuote() view returns(address)','function aavePool() view returns(address)','function uniV2Router() view returns(address)','function sushiV2Router() view returns(address)','function uniV3Factory() view returns(address)','function uniV3Router() view returns(address)','function aeroFactoryRegistry() view returns(address)','function aeroClassicFactory() view returns(address)','function aeroClassicRouter() view returns(address)','function aeroClFactory() view returns(address)','function aeroClRouter() view returns(address)']);
const feeAbi=parseAbi(['function getL1FeeUpperBound(uint256) view returns(uint256)','function getOperatorFee(uint256) view returns(uint256)']);
async function call(to,abi,functionName,args=[]){const data=encodeFunctionData({abi,functionName,args}),r=await rpc('eth_call',[{to,data},'latest']);return decodeFunctionResult({abi,functionName,data:r})}
async function ethUsd(){const c=new AbortController(),t=setTimeout(()=>c.abort(),3000);try{const r=await fetch('https://api.dexscreener.com/tokens/v1/base/'+WETH,{signal:c.signal,headers:{accept:'application/json'}});if(!r.ok)throw Error('price');const a=await r.json(),p=(Array.isArray(a)?a:[]).filter(x=>num(x.priceUsd)>0).sort((x,y)=>num(y.liquidity?.usd)-num(x.liquidity?.usd))[0];if(!p)throw Error('price');return num(p.priceUsd)}catch{return 2500}finally{clearTimeout(t)}}
function kind(m){if(m?.kind==='V2')return 0;if(m?.kind==='V3')return 1;if(m?.kind==='AERO_V2')return 2;if(m?.kind==='AERO_CL')return 3;throw Error('unsupported adapter')}
function leg(m,tin,tout){if(!m||!addr(m.pair)||!addr(tin)||!addr(tout))throw Error('invalid leg');return{kind:kind(m),venue:Number(m.venue||0),pair:m.pair,tokenIn:tin,tokenOut:tout,fee:Number(m.fee||0),tickSpacing:Number(m.tickSpacing||0),stable:Boolean(m.stable),minOut:BigInt(m.minOutRaw)}}
function txData(route,exact,minProfitRaw,deadline){const plan={quoteToken:route.quoteAddress,borrow:BigInt(exact.borrowRaw),minProfit:minProfitRaw,deadline:BigInt(deadline),buy:leg(exact.buyMeta,route.quoteAddress,route.assetAddress),sell:leg(exact.sellMeta,route.assetAddress,route.quoteAddress)};return encodeFunctionData({abi:receiverAbi,functionName:'executeArbitrage',args:[plan]})}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let next=0;async function worker(){while(true){const i=next++;if(i>=items.length)return;out[i]=await fn(items[i],i)}}await Promise.all(Array.from({length:Math.min(limit,items.length)},()=>worker()));return out}
async function receiverState(receiver,from,borrow){const code=await rpc('eth_getCode',[receiver,'latest']);if(!code||code==='0x')throw Error('receiver has no bytecode');const hash='0x'+createHash('sha256').update(String(code).toLowerCase()).digest('hex');if(norm(hash)!==norm(APPROVED_RUNTIME))throw Error('receiver runtime mismatch');const names=['owner','paused','maxBorrowRaw','authorizedQuote','aavePool','uniV2Router','sushiV2Router','uniV3Factory','uniV3Router','aeroFactoryRegistry','aeroClassicFactory','aeroClassicRouter','aeroClFactory','aeroClRouter'];const vals=await mapLimit(names,4,n=>call(receiver,viewAbi,n));const[owner,paused,maxBorrow,quote,aave,uv2,sv2,uv3f,uv3r,areg,aclf,aclr,aclF,aclR]=vals;if(norm(owner)!==norm(from))throw Error('receiver owner mismatch');if(paused)throw Error('receiver paused');if(BigInt(maxBorrow)<borrow)throw Error('receiver cap below route size');const expected=[[quote,USDC,'authorizedQuote'],[aave,AAVE,'aavePool'],[uv2,UNI_V2_ROUTER,'uniV2Router'],[sv2,SUSHI_V2_ROUTER,'sushiV2Router'],[uv3f,UNI_V3_FACTORY,'uniV3Factory'],[uv3r,UNI_V3_ROUTER,'uniV3Router'],[areg,AERO_REGISTRY,'aeroFactoryRegistry'],[aclf,AERO_CLASSIC_FACTORY,'aeroClassicFactory'],[aclr,AERO_CLASSIC_ROUTER,'aeroClassicRouter'],[aclF,AERO_CL_FACTORY,'aeroClFactory'],[aclR,AERO_CL_ROUTER,'aeroClRouter']];for(const[x,y,label]of expected)if(norm(x)!==norm(y))throw Error(label+' mismatch');return{runtimeHash:hash,maxBorrowRaw:BigInt(maxBorrow)}}
async function estimateFees(data,gas){const gasPrice=BigInt(await rpc('eth_gasPrice',[])),size=BigInt(Math.ceil((data.length-2)/2)+220);let l1=0n,op=0n;try{l1=BigInt(await call(GPO,feeAbi,'getL1FeeUpperBound',[size]))}catch{}try{op=BigInt(await call(GPO,feeAbi,'getOperatorFee',[gas]))}catch{}const total=gas*gasPrice+l1+op,px=await ethUsd();return{gasPriceWei:gasPrice.toString(),gasUnits:gas.toString(),l1FeeWei:l1.toString(),operatorFeeWei:op.toString(),totalGasWei:total.toString(),ethUsd:px,gasUsd:Number(total)/1e18*px}}
const safetyReserve=(borrowUsd,gasUsd)=>Math.max(0.10,Number(gasUsd||0)*0.35,Number(borrowUsd||0)*0.00001);

export async function prepareLive(b){const route=b?.route,receiver=b?.receiver,from=b?.from;if(!route||route.chainKey!=='base'||route.chainId!==8453)throw Error('Base execution only');if(!addr(receiver)||!addr(from)||!addr(route.quoteAddress)||!addr(route.assetAddress)||norm(route.quoteAddress)!==norm(USDC))throw Error('invalid Base USDC execution request');const fresh=await exactBase(route);if(fresh?.stage!=='EXACT_PASS'||fresh?.exact?.status!=='PASS')throw Error('fresh server EXACT_PASS required');const exact=fresh.exact,borrow=BigInt(exact.borrowRaw),borrowUsd=Number(route.optimalBorrow||route.borrowUsd||route.b);if(borrow<100000000n||borrow>250000000000n)throw Error('borrow outside policy');const state=await receiverState(receiver,from,borrow),head=BigInt(await rpc('eth_blockNumber',[])),proofBlock=BigInt(fresh.blockNumber||0),ageMs=Date.now()-Number(fresh.exactAt||0);if(!proofBlock||head>proofBlock+1n)throw Error('exact proof older than 1 block');if(ageMs>6500)throw Error('exact proof older than 6.5s');const deadline=Math.floor(Date.now()/1000)+60;let required=1n,data=txData(route,exact,required,deadline),gas=BigInt(await rpc('eth_estimateGas',[{from,to:receiver,data,value:'0x0'}],7000)),fees=await estimateFees(data,gas),reserve=safetyReserve(borrowUsd,fees.gasUsd);required=BigInt(Math.max(1,Math.ceil((fees.gasUsd+reserve)*1e6)));data=txData(route,exact,required,deadline);await rpc('eth_call',[{from,to:receiver,data,value:'0x0'},'latest'],8500);gas=BigInt(await rpc('eth_estimateGas',[{from,to:receiver,data,value:'0x0'}],8500));fees=await estimateFees(data,gas);reserve=safetyReserve(borrowUsd,fees.gasUsd);const required2=BigInt(Math.max(1,Math.ceil((fees.gasUsd+reserve)*1e6)));if(required2!==required){required=required2;data=txData(route,exact,required,deadline);await rpc('eth_call',[{from,to:receiver,data,value:'0x0'},'latest'],8500);gas=BigInt(await rpc('eth_estimateGas',[{from,to:receiver,data,value:'0x0'}],8500));fees=await estimateFees(data,gas);reserve=safetyReserve(borrowUsd,fees.gasUsd)}const expectedPostGasProfitUsd=fresh.exact.netBeforeGas-fees.gasUsd;if(expectedPostGasProfitUsd<=reserve)throw Error('dynamic protected-profit gate failed');return{ready:true,version:'10.4',chainId:8453,receiver,deadline,proofBlock:Number(proofBlock),currentBlock:Number(head),exactAgeMs:ageMs,maxStateAgeBlocks:1,safetyReserveUsd:reserve,requiredPreGasProfitUsd:Number(required)/1e6,minimumPostGasProfitUsd:Number(required)/1e6-fees.gasUsd,expectedPostGasProfitUsd,gas:fees,transaction:{to:receiver,data,value:'0x0',gas:'0x'+gas.toString(16)},freshExact:{...fresh,proofSource:'server'},runtimeHash:state.runtimeHash,rpcPolicy:RPC_POLICY,proofSummary:{freshServerExact:true,maxOneBlockOld:true,max6500msOld:true,receiverRuntime:true,receiverConstants:true,liveEthCall:true,liveEstimateGas:true,dynamicSafetyReserve:true,postGasGate:true}}}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'method_not_allowed'});try{return res.status(200).json(await prepareLive(req.body||{}))}catch(e){const s=sanitizeRpcError(e),message=e?.code?.startsWith?.('RPC_')?s.message:String(e?.message||e).slice(0,220);console.error('prepare-v104',s.code,message);return res.status(409).json({ready:false,error:e?.code||'prepare_failed',message,retryAfterMs:s.retryAfterMs||0})}}
