const PROVIDERS=[
  {name:'BasePublic',url:'https://mainnet.base.org'},
  {name:'PublicNode',url:'https://base-rpc.publicnode.com'}
];

export const RPC_POLICY='BasePublic primary → PublicNode failover · sequential · cooldown';
const states=PROVIDERS.map(p=>({...p,failures:0,cooldownUntil:0,lastError:null,lastGoodAt:0}));
const inflight=new Map();
const cache=new Map();

function safeText(x){let s=String(x??'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();if(!s)return'provider error';if(/cloudflare|just a moment|challenge-platform|cf-chl|doctype html/i.test(s))return'provider returned HTML/challenge';return s.slice(0,180)}
function makeError(code,message,retryAfterMs=0,provider=''){const e=new Error(message);e.code=code;e.retryAfterMs=retryAfterMs;e.provider=provider;return e}
function classify(status,text,type=''){const raw=String(text||''),html=/text\/html/i.test(type)||/^\s*</.test(raw)||/cloudflare|just a moment|challenge-platform|cf-chl/i.test(raw);if(html)return{code:'RPC_PROVIDER_HTML',message:'RPC provider challenge',cooldown:300000};if(status===429||/rate|limit|too many|quota/i.test(raw))return{code:'RPC_RATE_LIMIT',message:'RPC provider rate limited',cooldown:120000};if(status>=500)return{code:'RPC_PROVIDER_5XX',message:'RPC provider unavailable',cooldown:30000};return{code:'RPC_PROVIDER_ERROR',message:safeText(raw),cooldown:10000}}
function cacheTtl(method,params){if(method==='eth_chainId')return 60000;if(method==='eth_blockNumber')return 900;if(method==='eth_getCode')return 15000;if(method==='eth_call'&&typeof params?.[1]==='string'&&params[1].startsWith('0x'))return 30000;return 0}
function keyFor(method,params){try{return method+'|'+JSON.stringify(params)}catch{return method}}
function prune(){const now=Date.now();for(const[k,v]of cache)if(v.until<=now)cache.delete(k);while(cache.size>800)cache.delete(cache.keys().next().value)}

export function sanitizeRpcError(err){const code=String(err?.code||'RPC_ERROR'),retryAfterMs=Math.max(0,Number(err?.retryAfterMs)||0);let message=safeText(err?.message||err);if(code==='RPC_COOLDOWN')message='RPC providers cooling down';else if(code==='RPC_ALL_UNAVAILABLE')message='Base RPC providers temporarily unavailable';return{code,message,retryAfterMs}}

async function perform(method,params,timeout){const now=Date.now();if(!states.some(s=>s.cooldownUntil<=now)){const retry=Math.max(1000,Math.min(...states.map(s=>s.cooldownUntil-now).filter(x=>x>0))||5000);throw makeError('RPC_COOLDOWN','RPC providers cooling down',retry)}let last=null;for(const s of states){if(s.cooldownUntil>Date.now())continue;const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(s.url,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),signal:c.signal});const type=r.headers.get('content-type')||'',text=await r.text();let d;try{d=JSON.parse(text)}catch{d=null}if(r.ok&&d&&!d.error&&d.result!==undefined&&d.result!==null){s.failures=0;s.cooldownUntil=0;s.lastError=null;s.lastGoodAt=Date.now();return d.result}const cfy=classify(r.status,d?.error?.message||text,type);s.failures++;s.lastError=cfy.code;s.cooldownUntil=Date.now()+Math.min(300000,cfy.cooldown*Math.max(1,s.failures));last=makeError(cfy.code,cfy.message,s.cooldownUntil-Date.now(),s.name)}catch(err){const aborted=err?.name==='AbortError',cool=aborted?15000:10000;s.failures++;s.lastError=aborted?'RPC_TIMEOUT':'RPC_NETWORK';s.cooldownUntil=Date.now()+Math.min(120000,cool*Math.max(1,s.failures));last=makeError(s.lastError,aborted?'RPC request timed out':'RPC network request failed',s.cooldownUntil-Date.now(),s.name)}finally{clearTimeout(timer)}}if(last){last.code='RPC_ALL_UNAVAILABLE';last.message='Base RPC providers temporarily unavailable';throw last}throw makeError('RPC_ALL_UNAVAILABLE','Base RPC providers temporarily unavailable',5000)}

export async function baseRpc(method,params=[],timeout=4200,options={}){const key=keyFor(method,params),ttl=options.cache===false?0:cacheTtl(method,params),now=Date.now();if(ttl){const hit=cache.get(key);if(hit&&hit.until>now)return hit.value}if(!options.noDedupe&&inflight.has(key))return inflight.get(key);const p=perform(method,params,timeout).then(v=>{if(ttl){cache.set(key,{value:v,until:Date.now()+ttl});prune()}return v}).finally(()=>inflight.delete(key));if(!options.noDedupe)inflight.set(key,p);return p}
export async function latestBaseBlock(){return baseRpc('eth_blockNumber',[],3500)}
export function rpcHealth(){const now=Date.now();return{lastProvider:states.slice().sort((a,b)=>b.lastGoodAt-a.lastGoodAt)[0]?.name||null,providers:states.map(s=>({name:s.name,cooldownMs:Math.max(0,s.cooldownUntil-now),failures:s.failures,lastGoodAt:s.lastGoodAt,lastError:s.lastError}))}}
