const $=id=>document.getElementById(id),M=n=>'$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
let provider=null,wallet='',chain=0,receiverOK=false,selected=null,pkg=null,rows=[],lastBlock=0,scanning=false,watching=localStorage.getItem('fe941_watch')!=='0';
const freshPass=c=>!!(c?.exactEnvelope?.stage==='EXACT_PASS'&&c.exactEnvelope?.exact?.status==='PASS'&&Date.now()-Number(c.exactEnvelope?.exactAt||0)<45000);
function status(t,c=''){$('status').textContent=t;$('status').className=c}
function resetPkg(){pkg=null;$('send').disabled=true;$('packageState').textContent='No live transaction package';$('packageDetail').textContent='Nothing can be sent until every gate passes.'}
async function api(action,body){const r=await fetch('/api/engine?action='+encodeURIComponent(action),{method:body?'POST':'GET',headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined}),text=await r.text();let d;try{d=JSON.parse(text)}catch{throw Error('engine returned non-JSON '+r.status)}if(!r.ok||d?.ok===false)throw Error(d?.error||('HTTP '+r.status));return d}
function short(a){return a?a.slice(0,8)+'…'+a.slice(-6):'Not connected'}
function ui(){
  $('walletBadge').textContent=wallet?'WALLET CONNECTED':'WALLET DISCONNECTED';$('walletAccount').textContent=short(wallet);$('walletChain').textContent=wallet?(chain===8453?'Base · execution enabled':'Chain '+chain+' · switch to Base'):'Bitget / MetaMask supported';$('switch').disabled=!wallet||chain===8453;$('verifyReceiver').disabled=!wallet||chain!==8453;
  $('selectedRoute').textContent=selected?selected.assetSymbol+' · '+selected.buyDex+' → '+selected.sellDex+' · '+M(selected.borrowUsd):'No executable route selected';$('selectedProof').textContent=selected&&freshPass(selected)?'Fresh EXACT_PASS · final live proof required':'Waiting for a fresh EXACT_PASS';$('prepare').disabled=!(selected&&freshPass(selected)&&receiverOK&&chain===8453);if(!pkg)$('send').disabled=true;
}
function draw(){
  $('body').innerHTML=rows.length?rows.map(c=>{const pass=freshPass(c),e=c.exactEnvelope||{},net=e.exact?.netAfterGas,gate=e.stage||'SCREEN_ONLY';return `<tr><td><span class="tag">${c.assetSymbol}/USDC</span>${c.buyDex} → ${c.sellDex}<small>${c.sameDex?'same DEX · ':''}${Number(c.spreadBps||0).toFixed(1)} bps · block ${c.blockNumber}</small></td><td>${M(c.borrowUsd)}</td><td class="${c.screenNet>0?'good':'bad'}">${M(c.screenNet)}</td><td class="${net>0?'good':net<0?'bad':''}">${net==null?'—':M(net)}</td><td class="${pass?'good':gate==='EXACT_REJECT'?'bad':'warn'}">${pass?'EXACT_PASS':gate}</td><td><button data-id="${c.id}" ${pass?'':'disabled'}>${pass?'Select':'Locked'}</button></td></tr>`}).join(''):'<tr><td colspan="6">No screen candidate survived this block.</td></tr>';
  document.querySelectorAll('#body button:not(:disabled)').forEach(b=>b.onclick=()=>{selected=rows.find(x=>x.id===b.dataset.id)||null;resetPkg();status('Exact route selected. Verify receiver and run the final live proof.');ui()});
}
async function scan(force=false){if(scanning)return;scanning=true;$('scan').disabled=true;$('scan').textContent='Scanning…';try{const cap=Math.min(250000,Math.max(1000,+$('cap').value||250000)),d=await api('scan',{cap});lastBlock=d.blockNumber;rows=d.candidates||[];$('block').textContent=d.blockNumber;$('latency').textContent=d.latencyMs+' ms';$('candidates').textContent=d.candidateCount;$('passes').textContent=d.exactPasses;const exacts=rows.map(c=>c.exactEnvelope?.exact?.netAfterGas).filter(Number.isFinite);$('best').textContent=exacts.length?M(Math.max(...exacts)):'—';draw();selected=rows.find(freshPass)||null;resetPkg();if(selected){status('EXACT_PASS found · '+selected.assetSymbol+' '+M(selected.borrowUsd)+'. Verify receiver and run live proof.','good');beep()}else status((force?'Manual':'Block')+' scan '+d.blockNumber+' · '+(d.screenRouteCount??d.candidateCount)+' screen routes · '+(d.exactChecks??0)+' exact checks · no executable pass.');ui()}catch(e){status('Scan failed closed: '+e.message,'bad')}finally{scanning=false;$('scan').disabled=false;$('scan').textContent='Scan current block up to $250K'}}
function beep(){try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);g.gain.value=.03;o.frequency.value=880;o.start();setTimeout(()=>{o.stop();a.close()},140)}catch{}}
async function poll(){if(!watching||scanning||pkg)return;try{const d=await api('block');if(d.blockNumber&&d.blockNumber!==lastBlock)await scan()}catch{}}
function toggleWatch(){watching=!watching;localStorage.setItem('fe941_watch',watching?'1':'0');$('watch').textContent=watching?'AUTO BLOCK WATCH ON':'AUTO BLOCK WATCH OFF';$('watchState').textContent=$('watch').textContent}
async function connect(){provider=window.bitkeep?.ethereum||window.bitkeep?.ethreum||window.ethereum;if(!provider)return status('Open this page in Bitget Wallet or MetaMask browser to execute.','warn');try{const a=await provider.request({method:'eth_requestAccounts'});wallet=a?.[0]||'';chain=parseInt(await provider.request({method:'eth_chainId'}),16)||0;receiverOK=false;resetPkg();ui();status('Wallet connected.');if(chain===8453&&/^0x[0-9a-fA-F]{40}$/.test($('receiver').value.trim()))await verifyReceiver()}catch(e){status('Wallet connection cancelled: '+(e?.message||e),'bad')}}
async function switchBase(){if(!provider||!wallet)return;try{try{await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x2105'}]})}catch(e){if(Number(e?.code)!==4902)throw e;await provider.request({method:'wallet_addEthereumChain',params:[{chainId:'0x2105',chainName:'Base',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:['https://mainnet.base.org'],blockExplorerUrls:['https://basescan.org']}]});await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x2105'}]})}chain=8453;receiverOK=false;resetPkg();ui();status('Base selected.');if(/^0x[0-9a-fA-F]{40}$/.test($('receiver').value.trim()))await verifyReceiver()}catch(e){status('Base switch failed: '+e.message,'bad')}}
async function verifyReceiver(){const r=$('receiver').value.trim();if(!wallet||chain!==8453||!/^0x[0-9a-fA-F]{40}$/.test(r))return status('Connect the owner wallet on Base and enter the deployed V9 receiver.','bad');try{const d=await api('receiver',{receiver:r,owner:wallet});if(d.paused)throw Error('receiver is paused');receiverOK=true;localStorage.setItem('fe941_receiver',r);localStorage.setItem('fer',r);$('receiverState').textContent='Verified approved runtime + owner · ACTIVE · cap '+M(d.capUsd);status('Receiver verified.','good')}catch(e){receiverOK=false;$('receiverState').textContent='Receiver verification failed.';status('Receiver verification failed: '+e.message,'bad')}resetPkg();ui()}
async function prepare(){if(!selected||!freshPass(selected)||!receiverOK||chain!==8453)return status('Real-trade prerequisites incomplete.','bad');try{$('prepare').disabled=true;status('Rerunning exact + receiver eth_call + protected gas gate…','warn');const d=await api('prepare',{candidate:selected,receiver:$('receiver').value.trim(),from:wallet});if(!d.ready||!d.proofSummary?.freshServerExact||!d.proofSummary?.liveEthCall||!d.proofSummary?.postGasGate||!d.transaction?.data)throw Error(d.message||d.error||'live proof incomplete');pkg=d;$('packageState').textContent='LIVE PROOF PASS · WALLET READY';$('packageDetail').textContent='Expected post-gas '+M(d.expectedPostGasProfitUsd||0)+' · floor '+M(d.thresholdUsd||0)+' · expires '+new Date(d.deadline*1000).toLocaleTimeString();$('send').disabled=false;status('LIVE PROOF PASS. Review the wallet transaction before sending.','good')}catch(e){resetPkg();status('Preparation failed closed: '+e.message,'bad')}ui()}
async function rpc(method,params=[]){return(await api('rpc',{method,params})).result}
function quota(e){return /usage limit|1rpc|current plan|rate limit|quota/i.test(String(e?.message||e))}
async function sendWalletTx(tx){try{return await provider.request({method:'eth_sendTransaction',params:[tx]})}catch(e){if(!quota(e))throw e;status('Wallet RPC quota reached. Approve the signed Base relay fallback.','warn');const t={...tx,chainId:'0x2105'};if(!t.nonce)t.nonce=await rpc('eth_getTransactionCount',[wallet,'pending']);if(!t.gas){const est=BigInt(await rpc('eth_estimateGas',[t]));t.gas='0x'+(est*120n/100n).toString(16)}if(!t.gasPrice&&!t.maxFeePerGas)t.gasPrice=await rpc('eth_gasPrice',[]);let raw=await provider.request({method:'eth_signTransaction',params:[t]});if(raw&&typeof raw==='object')raw=raw.raw||raw.rawTransaction||raw.signedTransaction;if(typeof raw!=='string'||!raw.startsWith('0x'))throw Error('Wallet did not return a signed raw transaction');return rpc('eth_sendRawTransaction',[raw])}}
async function send(){if(!pkg?.ready||!selected||!freshPass(selected)||!receiverOK||chain!==8453||Date.now()/1000>=Number(pkg.deadline||0))return status('Send blocked; prepare a fresh live proof.','bad');try{$('send').disabled=true;const x=pkg.transaction,tx={from:wallet,to:x.to,data:x.data,value:x.value||'0x0',gas:x.gas};status('Opening wallet confirmation…','warn');const h=await sendWalletTx(tx);status('REAL TRADE SUBMITTED: '+h+' · waiting for receipt…','warn');for(let i=0;i<75;i++){await new Promise(r=>setTimeout(r,1600));const q=await rpc('eth_getTransactionReceipt',[h]);if(q){resetPkg();status(q.status==='0x0'?'Trade reverted atomically; gas was still spent.':'TRADE CONFIRMED ✅ '+h,q.status==='0x0'?'bad':'good');setTimeout(()=>scan(true),1000);return}}status('Transaction submitted; receipt still pending: '+h,'warn')}catch(e){status('Transaction not sent: '+e.message,'bad');$('send').disabled=false}}
async function hydrate(){
  $('watch').textContent=watching?'AUTO BLOCK WATCH ON':'AUTO BLOCK WATCH OFF';$('watchState').textContent=$('watch').textContent;$('receiver').value=localStorage.getItem('fe941_receiver')||localStorage.getItem('fer')||'';provider=window.bitkeep?.ethereum||window.bitkeep?.ethreum||window.ethereum;
  if(provider){try{const a=await provider.request({method:'eth_accounts'});wallet=a?.[0]||'';chain=parseInt(await provider.request({method:'eth_chainId'}),16)||0}catch{}provider.on?.('accountsChanged',a=>{wallet=a?.[0]||'';receiverOK=false;resetPkg();ui()});provider.on?.('chainChanged',h=>{chain=parseInt(h,16)||0;receiverOK=false;resetPkg();ui()})}
  ui();await scan(true);setInterval(poll,2400);
}
$('scan').onclick=()=>scan(true);$('watch').onclick=toggleWatch;$('connect').onclick=connect;$('switch').onclick=switchBase;$('verifyReceiver').onclick=verifyReceiver;$('prepare').onclick=prepare;$('send').onclick=send;$('receiver').oninput=()=>{receiverOK=false;resetPkg();ui()};hydrate();
