import { createHash } from 'node:crypto';
import { decodeFunctionResult, encodeFunctionData, parseAbi } from 'viem';

const USDC='0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913';
const UNI_FACTORY='0x33128a8fC17869897dcE68Ed026d694621f6FDfD';
const UNI_QUOTER='0x3d4e44Eb1374240CE5F1B871ab261CD16335B76a';
const AERO_FACTORY='0xf8f2eB4940CFE7d13603DDDD87f123820Fc061Ef';
const AERO_QUOTER='0x514c8B5f54112481E28028F1166Bd78501089259';
const SUSHI_ROUTER='0x6BDED42c6DA8FBf0d2bA55B2fa120C5e0c8D7891';
const V10='https://gigilabs-flash-edge-v10.vercel.app';
const APPROVED_RUNTIME='0x370c586265de600f83c972751bc334e493b07fe33ee100f84fb710763d732cad';
const ZERO='0x0000000000000000000000000000000000000000';
const ASSETS=[
 {symbol:'WETH',address:'0x4200000000000000000000000000000000000006'},
 {symbol:'cbBTC',address:'0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf'},
 {symbol:'cbETH',address:'0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22'},
 {symbol:'AERO',address:'0x940181a94A35A4569E4529A3CDfB74e38FD98631'}
];
const RPCS=['https://base-rpc.publicnode.com','https://mainnet.base.org','https://base.llamarpc.com','https://1rpc.io/base'];
const UF=parseAbi(['function getPool(address tokenA,address tokenB,uint24 fee) view returns(address pool)']);
const UQ=parseAbi(['function quoteExactInputSingle((address tokenIn,address tokenOut,uint256 amountIn,uint24 fee,uint160 sqrtPriceLimitX96) params) returns(uint256 amountOut,uint160 sqrtPriceX96After,uint32 initializedTicksCrossed,uint256 gasEstimate)']);
const AF=parseAbi(['function getPool(address tokenA,address tokenB,int24 tickSpacing) view returns(address pool)']);
const AQ=parseAbi(['function quoteExactInputSingle((address tokenIn,address tokenOut,uint256 amountIn,int24 tickSpacing,uint160 sqrtPriceLimitX96) params) returns(uint256 amountOut,uint160 sqrtPriceX96After,uint32 initializedTicksCrossed,uint256 gasEstimate)']);
const SR=parseAbi(['function factory() view returns(address)','function getAmountsOut(uint256 amountIn,address[] path) view returns(uint256[] amounts)']);
const VF=parseAbi(['function getPair(address tokenA,address tokenB) view returns(address pair)']);
const RX=parseAbi(['function owner() view returns(address)','function paused() view returns(bool)','function maxBorrowRaw() view returns(uint256)']);
let sushiFactory;
const metaCache=new Map();

function ok(res,data,status=200){res.status(status).json(data)}
function fail(res,message,status=500){res.status(status).json({ok:false,error:String(message)})}
function validAddress(x){return /^0x[0-9a-fA-F]{40}$/.test(String(x||''))}
function blockHex(n){return '0x'+n.toString(16)}
async function rpc(method,params=[]){let last='Base RPC unavailable';for(const url of RPCS){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),4500);const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),signal:c.signal});clearTimeout(t);const j=await r.json();if(r.ok&&!j.error&&j.result!==undefined)return j.result;last=j.error?.message||`HTTP ${r.status}`}catch(e){last=e?.message||String(e)}}throw Error(last)}
async function call(to,data,block='latest'){return await rpc('eth_call',[{to,data},block])}
async function latestBlock(){return Number(BigInt(await rpc('eth_blockNumber',[])))}
async function getSushiFactory(block){if(sushiFactory)return sushiFactory;const out=await call(SUSHI_ROUTER,encodeFunctionData({abi:SR,functionName:'factory'}),block);sushiFactory=decodeFunctionResult({abi:SR,functionName:'factory',data:out});return sushiFactory}
async function metasFor(asset,block){const cached=metaCache.get(asset.symbol);if(cached&&Date.now()-cached.at<600000)return cached.value;const uniFees=[100,500,3000,10000],ticks=[1,10,50,100,200];const [uni,aero,sushi]=await Promise.all([
 Promise.all(uniFees.map(async fee=>{try{const out=await call(UNI_FACTORY,encodeFunctionData({abi:UF,functionName:'getPool',args:[USDC,asset.address,fee]}),block);const pair=decodeFunctionResult({abi:UF,functionName:'getPool',data:out});return String(pair).toLowerCase()===ZERO?null:{venue:'Uniswap',pair,fee}}catch{return null}})),
 Promise.all(ticks.map(async tickSpacing=>{try{const out=await call(AERO_FACTORY,encodeFunctionData({abi:AF,functionName:'getPool',args:[USDC,asset.address,tickSpacing]}),block);const pair=decodeFunctionResult({abi:AF,functionName:'getPool',data:out});return String(pair).toLowerCase()===ZERO?null:{venue:'Aerodrome',pair,tickSpacing}}catch{return null}})),
 (async()=>{try{const fac=await getSushiFactory(block);const out=await call(fac,encodeFunctionData({abi:VF,functionName:'getPair',args:[USDC,asset.address]}),block);const pair=decodeFunctionResult({abi:VF,functionName:'getPair',data:out});return String(pair).toLowerCase()===ZERO?[]:[{venue:'Sushi',pair}]}catch{return []}})()
 ]);const value={Uniswap:uni.filter(Boolean),Aerodrome:aero.filter(Boolean),Sushi:sushi};metaCache.set(asset.symbol,{at:Date.now(),value});return value}
async function quoteOne(meta,tokenIn,tokenOut,amountIn,block){if(meta.venue==='Uniswap'){const out=await call(UNI_QUOTER,encodeFunctionData({abi:UQ,functionName:'quoteExactInputSingle',args:[{tokenIn,tokenOut,amountIn,fee:meta.fee,sqrtPriceLimitX96:0n}]}),block);return decodeFunctionResult({abi:UQ,functionName:'quoteExactInputSingle',data:out})[0]}if(meta.venue==='Aerodrome'){const out=await call(AERO_QUOTER,encodeFunctionData({abi:AQ,functionName:'quoteExactInputSingle',args:[{tokenIn,tokenOut,amountIn,tickSpacing:meta.tickSpacing,sqrtPriceLimitX96:0n}]}),block);return decodeFunctionResult({abi:AQ,functionName:'quoteExactInputSingle',data:out})[0]}const out=await call(SUSHI_ROUTER,encodeFunctionData({abi:SR,functionName:'getAmountsOut',args:[amountIn,[tokenIn,tokenOut]]}),block);const a=decodeFunctionResult({abi:SR,functionName:'getAmountsOut',data:out});return a[a.length-1]||0n}
async function bestQuote(metas,tokenIn,tokenOut,amountIn,block){const all=await Promise.all(metas.map(async meta=>{try{return{out:await quoteOne(meta,tokenIn,tokenOut,amountIn,block),meta}}catch{return null}}));let best=null;for(const x of all)if(x&&x.out>0n&&(!best||x.out>best.out))best=x;return best}
function sizes(cap){return [...new Set([1000,Math.min(2500,cap),Math.min(5000,cap),Math.round(cap*.5),cap].filter(x=>x>=1000&&x<=cap))].sort((a,b)=>a-b).slice(-4)}
async function routeFor(asset,borrowUsd,blockNumber,metas){const block=blockHex(blockNumber),amount=BigInt(Math.round(borrowUsd*1e6)),venues=['Uniswap','Aerodrome','Sushi'];const buys=await Promise.all(venues.map(async venue=>({venue,q:await bestQuote(metas[venue],USDC,asset.address,amount,block)})));const found=[];for(const buy of buys){if(!buy.q)continue;const sellVenues=venues.filter(v=>v!==buy.venue);const sells=await Promise.all(sellVenues.map(async venue=>({venue,q:await bestQuote(metas[venue],asset.address,USDC,buy.q.out,block)})));for(const sell of sells){if(!sell.q)continue;const returned=Number(sell.q.out)/1e6,flash=borrowUsd*.0005,screenNet=returned-borrowUsd-flash-.75,spreadBps=(returned/borrowUsd-1)*10000;if(screenNet<-8)continue;found.push({id:[asset.symbol,buy.venue,sell.venue,buy.q.meta.pair,sell.q.meta.pair].join(':'),k:'base',chain:'Base',chainId:8453,blockNumber,assetSymbol:asset.symbol,assetAddress:asset.address,quoteSymbol:'USDC',quoteAddress:USDC,buyDex:buy.venue,sellDex:sell.venue,bd:buy.venue,sd:sell.venue,buyPair:buy.q.meta.pair,sellPair:sell.q.meta.pair,borrowUsd,b:borrowUsd,optimalBorrow:borrowUsd,screenNet,spreadBps,gas:.75})}}return found}
async function exact(c){try{const r=await fetch(V10+'/api/exact',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(c)});const d=await r.json();return r.ok?d:{stage:'UNAVAILABLE',exact:{status:'BLOCKED',reason:d?.error||`HTTP ${r.status}`}}}catch(e){return{stage:'UNAVAILABLE',exact:{status:'BLOCKED',reason:e?.message||String(e)}}}}
async function scan(cap){const started=Date.now(),blockNumber=await latestBlock(),block=blockHex(blockNumber),ss=sizes(cap);const assetMetas=await Promise.all(ASSETS.map(async a=>[a,await metasFor(a,block)]));const routeSets=await Promise.all(assetMetas.flatMap(([asset,metas])=>ss.map(size=>routeFor(asset,size,blockNumber,metas))));const map=new Map();for(const c of routeSets.flat()){const prev=map.get(c.id);if(!prev||c.screenNet>prev.screenNet)map.set(c.id,c)}let candidates=[...map.values()].sort((a,b)=>b.screenNet-a.screenNet).slice(0,14);const top=candidates.filter(c=>c.screenNet>-2).slice(0,5);await Promise.all(top.map(async c=>{c.exactEnvelope=await exact(c)}));candidates.sort((a,b)=>(b.exactEnvelope?.exact?.netAfterGas??-999999)-(a.exactEnvelope?.exact?.netAfterGas??-999999)||b.screenNet-a.screenNet);return{ok:true,blockNumber,latencyMs:Date.now()-started,assets:ASSETS.length,venues:3,sizesTested:ss,candidateCount:candidates.length,exactPasses:candidates.filter(c=>c.exactEnvelope?.stage==='EXACT_PASS'&&c.exactEnvelope?.exact?.status==='PASS').length,candidates}}
async function receiverCheck(receiver,owner){if(!validAddress(receiver)||!validAddress(owner))throw Error('invalid receiver or owner');const code=await rpc('eth_getCode',[receiver,'latest']);if(!code||code==='0x')throw Error('no receiver bytecode');const hash='0x'+createHash('sha256').update(String(code).toLowerCase()).digest('hex');if(hash.toLowerCase()!==APPROVED_RUNTIME.toLowerCase())throw Error('receiver runtime mismatch');async function read(fn){const data=encodeFunctionData({abi:RX,functionName:fn});const out=await call(receiver,data,'latest');return decodeFunctionResult({abi:RX,functionName:fn,data:out})}const [chainOwner,paused,cap]=await Promise.all([read('owner'),read('paused'),read('maxBorrowRaw')]);if(String(chainOwner).toLowerCase()!==owner.toLowerCase())throw Error('owner mismatch');return{ok:true,owner:chainOwner,paused:Boolean(paused),capUsd:Number(cap)/1e6,runtimeHash:hash}}

export default async function handler(req,res){try{const action=String(req.query?.action||req.body?.action||'health');if(action==='health')return ok(res,{ok:true,engine:'Flash Edge V9.3',mode:'block-driven on-chain'});if(action==='block')return ok(res,{ok:true,blockNumber:await latestBlock(),serverTime:Date.now()});if(action==='scan'){const cap=Math.min(250000,Math.max(1000,Number(req.body?.cap)||10000));return ok(res,await scan(cap))}if(action==='receiver'){return ok(res,await receiverCheck(String(req.body?.receiver||''),String(req.body?.owner||'')))}if(action==='prepare'){const c=req.body?.candidate,env=c?.exactEnvelope;if(env?.stage!=='EXACT_PASS'||env?.exact?.status!=='PASS')return fail(res,'fresh EXACT_PASS required',409);const payload={route:{...c,chainKey:'base',optimalBorrow:Number(c.borrowUsd||c.b)},exact:env.exact,proofSource:'server',exactAt:env.exactAt,blockNumber:env.blockNumber,receiver:String(req.body?.receiver||''),from:String(req.body?.from||'')};const r=await fetch(V10+'/api/prepare',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();return ok(res,d,r.status)}if(action==='rpc'){const method=String(req.body?.method||''),allowed=new Set(['eth_getBalance','eth_getTransactionCount','eth_estimateGas','eth_gasPrice','eth_sendRawTransaction','eth_getTransactionReceipt','eth_chainId']);if(!allowed.has(method))return fail(res,'RPC method blocked',403);return ok(res,{ok:true,result:await rpc(method,Array.isArray(req.body?.params)?req.body.params:[])})}return fail(res,'unknown action',404)}catch(e){console.error(e);return fail(res,e?.message||String(e),503)}}