import{parseAbi,encodeFunctionData,decodeFunctionResult}from'viem';
const RPCS=['https://base-rpc.publicnode.com','https://mainnet.base.org','https://base.llamarpc.com','https://1rpc.io/base'];
const AAVE='0xA238Dd80C259a72e81d7e4664a9801593F98d1c5';
const UNI_QUOTER='0x3d4e44Eb1374240CE5F1B871ab261CD16335B76a';
const UNI_V3_FACTORY='0x33128a8fC17869897dcE68Ed026d694621f6FDfD';
const UNI_V2_ROUTER='0x4752ba5dbc23f44d87826276bf6fd6b1c372ad24';
const SUSHI_V2_ROUTER='0x6BDED42c6DA8FBf0d2bA55B2fa120C5e0c8D7891';
const AERO_FACTORY='0x420DD381b31aEf6683db6B902084cB0FFECe40Da';
const REG='0x5C3F18F06CC09CA1910767A34a20F771039E37C0';
const GEN={
'0x5e7bb104d84c7cb9b682aac2f3d509f5f406809a':['0x254cF9E1E6e233aa1AC962CB9B05b2cfeAaE15b0','AERO_CL_LEGACY','AERODROME LEGACY SLIPSTREAM'],
'0xade65c38cd4849adba595a4323a8c7ddfe89716a':['0x3d4C22254F86f64B7eC90ab8F7aeC1FBFD271c6C','AERO_CL_CAPS','AERODROME CAPS SLIPSTREAM'],
'0xf8f2eb4940cfe7d13603dddd87f123820fc061ef':['0x514c8B5f54112481E28028F1166Bd78501089259','AERO_CL','AERODROME CURRENT SLIPSTREAM']
};
const norm=s=>String(s||'').toLowerCase(),raw=v=>v.startsWith('0x')?v.slice(2):v,pad=v=>raw(v).toLowerCase().padStart(64,'0'),addr=v=>'0x'+raw(v).slice(-40).toLowerCase();
const units=(n,d)=>BigInt(Math.round(n*1e6))*10n**BigInt(d)/1000000n,toNum=(n,d)=>Number(n)/10**d,minOut=x=>x*9980n/10000n;
const qd=(a,b,n,f)=>'0xc6a5026a'+pad(a)+pad(b)+pad('0x'+n.toString(16))+pad('0x'+f.toString(16))+'0'.repeat(64);
async function one(url,method,params,ms=1800){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),signal:c.signal});const d=await r.json();if(!r.ok||d.error||typeof d.result!=='string')throw Error(d.error?.message||'RPC');return d.result}finally{clearTimeout(t)}}
async function rpc(method,params,ms=2000){try{return await Promise.any(RPCS.map(u=>one(u,method,params,ms)))}catch{throw Error('Base RPC race failed')}}
const erc20=parseAbi(['function decimals() view returns(uint8)']);
const pairAbi=parseAbi(['function token0() view returns(address)','function token1() view returns(address)','function factory() view returns(address)']);
const v2pairAbi=parseAbi(['function token0() view returns(address)','function token1() view returns(address)','function factory() view returns(address)','function getReserves() view returns(uint112,uint112,uint32)']);
const routerAbi=parseAbi(['function factory() view returns(address)']);
const v3poolAbi=parseAbi(['function token0() view returns(address)','function token1() view returns(address)','function factory() view returns(address)','function fee() view returns(uint24)']);
const v3factoryAbi=parseAbi(['function getPool(address,address,uint24) view returns(address)']);
const ca=parseAbi(['function stable() view returns(bool)','function factory() view returns(address)','function getAmountOut(uint256,address) view returns(uint256)']);
const cl=parseAbi(['function factory() view returns(address)','function tickSpacing() view returns(int24)']);
const clf=parseAbi(['function getPool(address,address,int24) view returns(address)']);
const cq=parseAbi(['function quoteExactInputSingle((address tokenIn,address tokenOut,uint256 amountIn,int24 tickSpacing,uint160 sqrtPriceLimitX96) params) returns(uint256,uint160,uint32,uint256)']);
const ra=parseAbi(['function isPoolFactoryApproved(address) view returns(bool)']);
async function call(block,to,abi,functionName,args=[]){const data=encodeFunctionData({abi,functionName,args}),r=await rpc('eth_call',[{to,data},block]);return decodeFunctionResult({abi,functionName,data:r})}
async function qV2(block,pair,tin,tout,amt,dex){if(!/Uniswap|Sushi/.test(dex))throw Error('not V2');const router=dex==='Sushi'?SUSHI_V2_ROUTER:UNI_V2_ROUTER;const[t0,t1,pf,rf,rs]=await Promise.all([call(block,pair,v2pairAbi,'token0'),call(block,pair,v2pairAbi,'token1'),call(block,pair,v2pairAbi,'factory'),call(block,router,routerAbi,'factory'),call(block,pair,v2pairAbi,'getReserves')]);if(norm(pf)!==norm(rf))throw Error('V2 factory mismatch');if(!((norm(tin)===norm(t0)&&norm(tout)===norm(t1))||(norm(tin)===norm(t1)&&norm(tout)===norm(t0))))throw Error('V2 token mismatch');const r0=BigInt(rs[0]),r1=BigInt(rs[1]),ri=norm(tin)===norm(t0)?r0:r1,ro=norm(tin)===norm(t0)?r1:r0;if(ri<=0n||ro<=0n)throw Error('empty V2 reserves');const awf=amt*997n,out=awf*ro/(ri*1000n+awf);if(out<=0n)throw Error('zero V2 quote');return{out,minOut:minOut(out),adapter:dex+' V2 SERVER',kind:'V2',venue:dex==='Sushi'?1:0,pair,factory:pf,fee:0,tickSpacing:0,stable:false}}
async function qV3(block,pair,tin,tout,amt){const[t0,t1,factory,feeRaw]=await Promise.all([call(block,pair,v3poolAbi,'token0'),call(block,pair,v3poolAbi,'token1'),call(block,pair,v3poolAbi,'factory'),call(block,pair,v3poolAbi,'fee')]);const fee=Number(feeRaw);if(norm(factory)!==norm(UNI_V3_FACTORY))throw Error('V3 factory mismatch');if(!((norm(tin)===norm(t0)&&norm(tout)===norm(t1))||(norm(tin)===norm(t1)&&norm(tout)===norm(t0))))throw Error('V3 token mismatch');if(![100,500,3000,10000].includes(fee))throw Error('unsupported V3 fee');const canonical=await call(block,UNI_V3_FACTORY,v3factoryAbi,'getPool',[tin,tout,fee]);if(norm(canonical)!==norm(pair))throw Error('V3 pool mismatch');const qr=await rpc('eth_call',[{to:UNI_QUOTER,data:qd(tin,tout,amt,fee)},block]),out=BigInt('0x'+raw(qr).slice(0,64));if(out<=0n)throw Error('zero V3 quote');return{out,minOut:minOut(out),adapter:'UNISWAP V3 SERVER',kind:'V3',venue:0,pair,factory,fee,tickSpacing:0,stable:false}}
async function qAero(block,pair,tin,tout,amt){const[t0,t1]=await Promise.all([call(block,pair,pairAbi,'token0'),call(block,pair,pairAbi,'token1')]);if(!((norm(tin)===norm(t0)&&norm(tout)===norm(t1))||(norm(tin)===norm(t1)&&norm(tout)===norm(t0))))throw Error('Aerodrome token mismatch');try{const[stable,factory]=await Promise.all([call(block,pair,ca,'stable'),call(block,pair,ca,'factory')]);if(norm(factory)!==norm(AERO_FACTORY))throw Error('not classic');const out=await call(block,pair,ca,'getAmountOut',[amt,tin]);if(out<=0n)throw Error('zero Aerodrome classic quote');return{out,minOut:minOut(out),adapter:stable?'AERODROME STABLE SERVER':'AERODROME VOLATILE SERVER',kind:'AERO_V2',venue:0,pair,factory,fee:0,tickSpacing:0,stable:Boolean(stable)}}catch{const[factory,tickRaw]=await Promise.all([call(block,pair,cl,'factory'),call(block,pair,cl,'tickSpacing')]),tick=Number(tickRaw);if(!Number.isFinite(tick)||tick<=0)throw Error('invalid Slipstream tick spacing');const g=GEN[norm(factory)];if(!g){let approved=false;try{approved=await call(block,REG,ra,'isPoolFactoryApproved',[factory])}catch{}throw Error((approved?'approved':'unapproved')+' Aerodrome CL factory not mapped: '+factory)}const canonical=await call(block,factory,clf,'getPool',[tin,tout,tick]);if(norm(canonical)!==norm(pair))throw Error('Slipstream pool mismatch');const qr=await rpc('eth_call',[{to:g[0],data:encodeFunctionData({abi:cq,functionName:'quoteExactInputSingle',args:[{tokenIn:tin,tokenOut:tout,amountIn:amt,tickSpacing:tick,sqrtPriceLimitX96:0n}]})},block]),decoded=decodeFunctionResult({abi:cq,functionName:'quoteExactInputSingle',data:qr}),out=decoded[0];if(out<=0n)throw Error('zero Slipstream quote');return{out,minOut:minOut(out),adapter:g[2],kind:g[1],venue:0,pair,factory,fee:0,tickSpacing:tick,stable:false}}}
async function quote(block,pair,dex,tin,tout,amt){if(dex==='Aerodrome')return qAero(block,pair,tin,tout,amt);try{return await qV2(block,pair,tin,tout,amt,dex)}catch{return qV3(block,pair,tin,tout,amt)}}
export async function exactBase(o,onStage=()=>{}){let phase='HEAD';try{onStage(phase);const block=await rpc('eth_blockNumber',[]);phase='META';onStage(phase);const[feeRaw,sdRaw,bdRaw]=await Promise.all([rpc('eth_call',[{to:AAVE,data:'0x074b2e43'},block]),rpc('eth_call',[{to:o.quoteAddress,data:encodeFunctionData({abi:erc20,functionName:'decimals'})},block]),rpc('eth_call',[{to:o.assetAddress,data:encodeFunctionData({abi:erc20,functionName:'decimals'})},block])]),fee=Number(BigInt(feeRaw)),sd=Number(BigInt(sdRaw)),bd=Number(BigInt(bdRaw));if(sd<0||sd>36||bd<0||bd>36)throw Error('invalid token decimals');const amt=units(o.optimalBorrow,sd);phase='BUY';onStage(phase);const buy=await quote(block,o.buyPair,o.buyDex,o.quoteAddress,o.assetAddress,amt);phase='SELL';onStage(phase);const sell=await quote(block,o.sellPair,o.sellDex,o.assetAddress,o.quoteAddress,buy.out),rt=toNum(sell.out,sd),flash=toNum(amt*BigInt(Math.max(0,Math.round(fee)))/10000n,sd),gasUsd=Math.max(.01,Number(o.gas)||.75),netBeforeGas=rt-o.optimalBorrow-flash,net=netBeforeGas-gasUsd,threshold=Math.max(10,o.optimalBorrow*.0005),old=[buy.kind,sell.kind].some(k=>k==='AERO_CL_LEGACY'||k==='AERO_CL_CAPS'),stage=net>threshold?(old?'ADAPTER_BLOCKED':'EXACT_PASS'):net>0?'WATCHLIST_EXACT':'EXACT_REJECT';return{stage,chainKey:'base',chain:'Base',blockNumber:Number(BigInt(block)),exactAt:Date.now(),aaveFlashFeeBps:fee,thresholdUsd:threshold,watchlistOnly:stage==='WATCHLIST_EXACT',executionEligible:stage==='EXACT_PASS',signingEnabled:false,exact:{status:'PASS',netAfterGas:net,netBeforeGas,gasUsd,flashFee:flash,roundTrip:rt,roundTripBps:(rt/o.optimalBorrow-1)*10000,buyAdapter:buy.adapter,sellAdapter:sell.adapter,buyKind:buy.kind,sellKind:sell.kind,buyOutRaw:buy.out.toString(),sellOutRaw:sell.out.toString(),borrowRaw:amt.toString(),quoteDecimals:sd,assetDecimals:bd,buyMeta:{kind:buy.kind,venue:buy.venue,pair:buy.pair,factory:buy.factory,fee:buy.fee,tickSpacing:buy.tickSpacing,stable:buy.stable,minOutRaw:buy.minOut.toString()},sellMeta:{kind:sell.kind,venue:sell.venue,pair:sell.pair,factory:sell.factory,fee:sell.fee,tickSpacing:sell.tickSpacing,stable:sell.stable,minOutRaw:sell.minOut.toString()},reason:stage==='ADAPTER_BLOCKED'?'Exact quote succeeded; legacy/intermediate Slipstream remains execution-blocked.':undefined}}}catch(e){return{stage:'UNAVAILABLE',chainKey:'base',chain:'Base',executionEligible:false,signingEnabled:false,exact:{status:'BLOCKED',reason:'SERVER '+phase+' · '+(e?.message||'Base exact unavailable')}}}}

export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'method_not_allowed'});return res.status(200).json(await exactBase(req.body||{}))}
